import { useState } from 'react'
import { observer } from 'mobx-react-lite'
import { money, uid } from '../../lib/utils'
import { Empty } from '../ui/Empty'
import { Icon } from '../ui/Icon'
import { PageHeader } from '../ui/PageHeader'

export const Inventory = observer(({ store }) => {
  const [search, setSearch] = useState('')
  const [form, setForm] = useState({ name: '', sku: '', unit: 'Cái', quantity: 0, reorderPoint: 10, unitPrice: 0 })
  const products = store.data.products.filter(product => `${product.name} ${product.sku}`.toLowerCase().includes(search.toLowerCase()))
  const add = (event) => { event.preventDefault(); if (!form.name || !form.sku) return; store.addProduct(form); setForm({ name: '', sku: '', unit: 'Cái', quantity: 0, reorderPoint: 10, unitPrice: 0 }) }
  const remove = (id) => { if (confirm('Xóa vật tư này?')) store.removeProduct(id) }
  return <><PageHeader eyebrow="KHO VẬT TƯ" title="Danh mục vật tư" description="Theo dõi tồn kho và mức cảnh báo ngay trên thiết bị." /><div className="two-col"><section className="panel"><div className="panel-heading"><div><h3>Thêm vật tư</h3><span>Master data của kho</span></div></div><form className="form-grid" onSubmit={add}><label className="span-2">Tên vật tư<input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Ví dụ: Dầu nhớt" required /></label><label>Mã SKU<input value={form.sku} onChange={e => setForm({ ...form, sku: e.target.value })} placeholder="VT-001" required /></label><label>Đơn vị<select value={form.unit} onChange={e => setForm({ ...form, unit: e.target.value })}><option>Cái</option><option>Kg</option><option>Can</option><option>Thùng</option><option>Đôi</option><option>Bộ</option></select></label><label>Số lượng<input type="number" min="0" value={form.quantity} onChange={e => setForm({ ...form, quantity: e.target.value })} /></label><label>Mức đặt lại<input type="number" min="0" value={form.reorderPoint} onChange={e => setForm({ ...form, reorderPoint: e.target.value })} /></label><label className="span-2">Đơn giá<input type="number" min="0" value={form.unitPrice} onChange={e => setForm({ ...form, unitPrice: e.target.value })} /></label><button className="button primary span-2"><Icon name="plus" /> Thêm vật tư</button></form></section><section className="panel"><div className="panel-heading"><div><h3>Danh sách vật tư</h3><span>{store.data.products.length} loại trong kho</span></div><div className="search-box"><Icon name="search" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="Tìm tên hoặc SKU" /></div></div><div className="table-wrap"><table><thead><tr><th>Vật tư</th><th>Tồn</th><th>Đặt lại</th><th>Đơn giá</th><th /></tr></thead><tbody>{products.map(product => <tr key={product.id}><td><b>{product.name}</b><small>{product.sku} · {product.unit}</small></td><td><strong className={product.quantity <= product.reorderPoint ? 'danger-text' : ''}>{product.quantity}</strong></td><td>{product.reorderPoint}</td><td>{money(product.unitPrice)}</td><td><button className="icon-button danger-hover" onClick={() => remove(product.id)}><Icon name="trash" /></button></td></tr>)}</tbody></table>{!products.length && <Empty title="Không tìm thấy vật tư" text="Thử từ khóa khác." />}</div></section></div></>
})
