import { useState } from 'react'
import { observer } from 'mobx-react-lite'
import { PageHeader } from '../ui/PageHeader'
import { Icon } from '../ui/Icon'

export const CustomerManager = observer(({ store }) => {
  const [form, setForm] = useState({ name: '', code: '', phone: '', address: '' })
  const add = (event) => { event.preventDefault(); if (!form.name.trim()) return; store.addCustomer(form); setForm({ name: '', code: '', phone: '', address: '' }) }
  return <><PageHeader eyebrow="DANH MỤC" title="Khách hàng" description="Thêm mới khách hàng và dùng ngay trong phiếu xuất." /><div className="two-col"><section className="panel"><div className="panel-heading"><div><h3>Thêm khách hàng</h3><span>Không có danh sách cố định</span></div></div><form className="form-grid" onSubmit={add}><label className="span-2">Tên khách hàng<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Công ty / đơn vị nhận hàng" /></label><label>Mã khách hàng<input value={form.code} onChange={e => setForm({ ...form, code: e.target.value })} placeholder="KH-001" /></label><label>Số điện thoại<input value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} placeholder="09..." /></label><label className="span-2">Địa chỉ<input value={form.address} onChange={e => setForm({ ...form, address: e.target.value })} placeholder="Địa chỉ" /></label><button className="button primary span-2"><Icon name="plus" /> Lưu khách hàng</button></form></section><section className="panel"><div className="panel-heading"><div><h3>Danh sách khách hàng</h3><span>Thêm xong có thể lọc phiếu ngay</span></div></div><div className="customer-list">{store.data.customers.map(customer => <div className="customer-row" key={customer.id}><div className="avatar soft">{customer.name.slice(0, 1).toUpperCase()}</div><div className="grow"><b>{customer.name}</b><span>{customer.code || 'Chưa có mã'} · {customer.phone || 'Chưa có SĐT'}</span></div><span className={customer.status === 'Active' ? 'badge green' : 'badge gray'}>{customer.status === 'Active' ? 'Đang dùng' : 'Tạm dừng'}</span><button className="text-button" onClick={() => store.toggleCustomer(customer.id)}>{customer.status === 'Active' ? 'Tạm dừng' : 'Kích hoạt'}</button></div>)}</div></section></div></>
})
