import { observer } from 'mobx-react-lite'
import { dateText, money } from '../../lib/utils'
import { Empty } from '../ui/Empty'
import { Icon } from '../ui/Icon'
import { PageHeader } from '../ui/PageHeader'
import { Stat } from '../ui/Stat'

export const Dashboard = observer(({ store }) => {
  const { data, lowStock } = store
  const recent = [...data.orders].sort((a, b) => b.date.localeCompare(a.date)).slice(0, 5)
  return <><PageHeader eyebrow="TỔNG QUAN" title="Chào buổi sáng, admin" description="Đây là tình hình kho trên thiết bị hiện tại." action={<button className="button primary" onClick={() => store.setNav('outbound')}><Icon name="plus" /> Tạo phiếu xuất</button>} /><div className="stats-grid"><Stat label="Tổng giá trị kho" value={money(store.stockValue)} hint={`${data.products.length} loại vật tư`} /><Stat label="Tổng số lượng" value={data.products.reduce((s, p) => s + p.quantity, 0).toLocaleString('vi-VN')} hint="Tồn hiện tại" tone="blue" /><Stat label="Vật tư sắp hết" value={lowStock.length} hint={lowStock.length ? 'Cần bổ sung' : 'Mọi thứ ổn định'} tone={lowStock.length ? 'orange' : 'green'} /><Stat label="Tổng phiếu" value={data.orders.length} hint="Nhập và xuất kho" tone="purple" /></div><div className="dashboard-grid"><section className="panel"><div className="panel-heading"><div><h3>Phiếu gần đây</h3><span>Hoạt động mới nhất</span></div><button className="text-button" onClick={() => store.setNav('outbound')}>Xem tất cả →</button></div>{recent.length ? <div className="order-list">{recent.map(order => <div className="order-row" key={order.id}><div className={`type-dot ${order.type === 'Outbound' ? 'out' : 'in'}`}>{order.type === 'Outbound' ? '↑' : '↓'}</div><div className="grow"><b>{order.orderNumber}</b><span>{order.customerName || order.partnerName || 'Không có đối tác'}</span></div><span className={order.type === 'Outbound' ? 'badge blue' : 'badge green'}>{order.type === 'Outbound' ? 'Xuất kho' : 'Nhập kho'}</span><time>{dateText(order.date)}</time></div>)}</div> : <Empty title="Chưa có phiếu" text="Tạo phiếu đầu tiên để bắt đầu." />}</section><section className="panel"><div className="panel-heading"><div><h3>Cảnh báo tồn kho</h3><span>Vật tư dưới mức đặt lại</span></div><button className="text-button" onClick={() => store.setNav('inventory')}>Mở kho →</button></div>{lowStock.length ? <div className="low-list">{lowStock.map(product => <div className="low-row" key={product.id}><div className="product-symbol">{product.name.slice(0, 1)}</div><div className="grow"><b>{product.name}</b><span>{product.sku}</span></div><strong className="danger-text">{product.quantity} {product.unit}</strong></div>)}</div> : <Empty title="Kho đang ổn định" text="Không có vật tư dưới mức cảnh báo." />}</section></div></>
})
